/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadProductImageRouteImport } from './routes/upload/product-image'
import { Route as UploadEmployeePhotoRouteImport } from './routes/upload/employee-photo'
import { Route as UploadEmployeeDocumentRouteImport } from './routes/upload/employee-document'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadProductImageRoute = UploadProductImageRouteImport.update({
  id: '/upload/product-image',
  path: '/upload/product-image',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadEmployeePhotoRoute = UploadEmployeePhotoRouteImport.update({
  id: '/upload/employee-photo',
  path: '/upload/employee-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadEmployeeDocumentRoute = UploadEmployeeDocumentRouteImport.update({
  id: '/upload/employee-document',
  path: '/upload/employee-document',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/products': typeof ProductsRoute
  '/staff': typeof StaffRoute
  '/transactions': typeof TransactionsRoute
  '/upload/employee-document': typeof UploadEmployeeDocumentRoute
  '/upload/employee-photo': typeof UploadEmployeePhotoRoute
  '/upload/product-image': typeof UploadProductImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/products': typeof ProductsRoute
  '/staff': typeof StaffRoute
  '/transactions': typeof TransactionsRoute
  '/upload/employee-document': typeof UploadEmployeeDocumentRoute
  '/upload/employee-photo': typeof UploadEmployeePhotoRoute
  '/upload/product-image': typeof UploadProductImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRoute
  '/dashboard': typeof DashboardRoute
  '/products': typeof ProductsRoute
  '/staff': typeof StaffRoute
  '/transactions': typeof TransactionsRoute
  '/upload/employee-document': typeof UploadEmployeeDocumentRoute
  '/upload/employee-photo': typeof UploadEmployeePhotoRoute
  '/upload/product-image': typeof UploadProductImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/dashboard'
    | '/products'
    | '/staff'
    | '/transactions'
    | '/upload/employee-document'
    | '/upload/employee-photo'
    | '/upload/product-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/dashboard'
    | '/products'
    | '/staff'
    | '/transactions'
    | '/upload/employee-document'
    | '/upload/employee-photo'
    | '/upload/product-image'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/dashboard'
    | '/products'
    | '/staff'
    | '/transactions'
    | '/upload/employee-document'
    | '/upload/employee-photo'
    | '/upload/product-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRoute
  DashboardRoute: typeof DashboardRoute
  ProductsRoute: typeof ProductsRoute
  StaffRoute: typeof StaffRoute
  TransactionsRoute: typeof TransactionsRoute
  UploadEmployeeDocumentRoute: typeof UploadEmployeeDocumentRoute
  UploadEmployeePhotoRoute: typeof UploadEmployeePhotoRoute
  UploadProductImageRoute: typeof UploadProductImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/product-image': {
      id: '/upload/product-image'
      path: '/upload/product-image'
      fullPath: '/upload/product-image'
      preLoaderRoute: typeof UploadProductImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/employee-photo': {
      id: '/upload/employee-photo'
      path: '/upload/employee-photo'
      fullPath: '/upload/employee-photo'
      preLoaderRoute: typeof UploadEmployeePhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/employee-document': {
      id: '/upload/employee-document'
      path: '/upload/employee-document'
      fullPath: '/upload/employee-document'
      preLoaderRoute: typeof UploadEmployeeDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRoute,
  DashboardRoute: DashboardRoute,
  ProductsRoute: ProductsRoute,
  StaffRoute: StaffRoute,
  TransactionsRoute: TransactionsRoute,
  UploadEmployeeDocumentRoute: UploadEmployeeDocumentRoute,
  UploadEmployeePhotoRoute: UploadEmployeePhotoRoute,
  UploadProductImageRoute: UploadProductImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
